In [1]:
from locale import atof, setlocale, LC_NUMERIC
setlocale(LC_NUMERIC, '')

setlocale(LC_NUMERIC, 'French_Canada.1252')

'French_Canada.1252'

In [2]:
import pandas as pd

major_data = pd.read_csv('graduates-major-data.csv', delimiter = ";", decimal=",")

# 1

In [3]:
task_1_data = major_data.loc[(major_data['P_N'] >= 30) & (major_data['P_POZIOM'] == "2")]

task_1_data = task_1_data.groupby(['P_KIERUNEK_ID', 'P_KIERUNEK_NAZWA', 'P_NAZWA_UCZELNI'], as_index=False)["P_ME_ZAR_P5"].median()

task_1_data = task_1_data[['P_KIERUNEK_ID', "P_KIERUNEK_NAZWA", "P_NAZWA_UCZELNI", "P_ME_ZAR_P5"]]

task_1_data = task_1_data.sort_values(by='P_ME_ZAR_P5', ascending=False).head(10)

task_1_data["KIERUNEK"] = task_1_data["P_KIERUNEK_NAZWA"].astype("str") + "(" + task_1_data["P_KIERUNEK_ID"].astype("str") + ")"

In [4]:
list(task_1_data["KIERUNEK"])

['Informatyka(29646)',
 'Informatyka(22827)',
 'Informatyka(23912)',
 'Informatyka(7604)',
 'Informatyka(29464)',
 'Automatyka i robotyka(27839)',
 'Informatyka(8507)',
 'Informatyka(25706)',
 'Informatyka(27860)',
 'Informatyka(28422)']

In [5]:
task_1_data

,P_KIERUNEK_ID,P_KIERUNEK_NAZWA,P_NAZWA_UCZELNI,P_ME_ZAR_P5,KIERUNEK
1867,29646,Informatyka,Akademia Górniczo-Hutnicza im. Stanisława Stas...,13932.48,Informatyka(29646)
683,22827,Informatyka,Politechnika Warszawska,12962.67,Informatyka(22827)
922,23912,Informatyka,Politechnika Poznańska,12874.23,Informatyka(23912)
33,7604,Informatyka,Politechnika Warszawska,12832.00,Informatyka(7604)
1856,29464,Informatyka,Polsko-Japońska Wyższa Szkoła Technik Komputer...,12740.78,Informatyka(29464)
1622,27839,Automatyka i robotyka,Akademia Górniczo-Hutnicza im. Stanisława Stas...,12716.30,Automatyka i robotyka(27839)
58,8507,Informatyka,Politechnika Wrocławska,12416.86,Informatyka(8507)
1238,25706,Informatyka,Politechnika Gdańska,12239.22,Informatyka(25706)
1628,27860,Informatyka,Akademia Górniczo-Hutnicza im. Stanisława Stas...,12222.68,Informatyka(27860)
1723,28422,Informatyka,Wojskowa Akademia Techniczna im. Jarosława Dąb...,11963.65,Informatyka(28422)

In [6]:
import plotly.express as px
import plotly

graph_data = task_1_data

fig = px.bar(
    graph_data, 
    x = 'KIERUNEK', 
    y = 'P_ME_ZAR_P5',
    color = 'P_NAZWA_UCZELNI',
    
    category_orders=dict(group=list(task_1_data["KIERUNEK"])),
    
    title = "TOP 10 Kierunków z najwyższymi zarobkami (5 lat po ukończeniu studiów II stopnia)",

    labels={
        "P_ME_ZAR_P5": "Średnie zarobki po 5 latach od ukończenia studiów [PLN]",
        "KIERUNEK": "Kierunek",
        "P_NAZWA_UCZELNI": "Szkoła wyższa",
    }
)

fig.update_layout(xaxis_categoryorder = 'total descending')

plotly.offline.plot(fig, filename='TOP_10_Kierunków_zarobki.html')

'TOP_10_Kierunków_zarobki.html'

In [7]:
task_2_data = major_data.loc[
    (major_data["P_KIERUNEK_NAZWA"].str.lower().str.contains("informatyka"))
    & (major_data['P_N'].astype("int") > 25)
    & ((major_data['P_POZIOM'] == "1") | (major_data['P_POZIOM'] == "2"))
]

task_2_data = task_2_data[[
    'P_N', 
    
    'P_POZIOM', 
    'P_POZIOM_TEKST_PL',
    'P_N_SEMESTR',
    
    'P_NAZWA_UCZELNI',
    'P_KIERUNEK_NAZWA',
    
    'P_WWZ_MIES_60', 
    'P_E_ZAR_ETAT_P5', 
    'P_ZAR_ETAT_MAX', 
    'P_PROC_MIES_BEZR',
#     'P_PROC_MIES_BEZR_P1',
#     'P_PROC_MIES_BEZR_P2',
#     'P_PROC_MIES_BEZR_P3',
#     'P_PROC_MIES_BEZR_P4',
#     'P_PROC_MIES_BEZR_P5',
    'P_PROC_MIES_BEZR_DOSW',
#     'P_PROC_MIES_BEZR_DOSW_P1',
#     'P_PROC_MIES_BEZR_DOSW_P2',
#     'P_PROC_MIES_BEZR_DOSW_P3',
#     'P_PROC_MIES_BEZR_DOSW_P4',
#     'P_PROC_MIES_BEZR_DOSW_P5',
    
    'P_WWB',
#     'P_WWB_P1',
#     'P_WWB_P2',
#     'P_WWB_P3',
#     'P_WWB_P4',
#     'P_WWB_P5',
    
#     'P_CZY_ETAT',
#     'P_CZY_ETAT_P1',
#     'P_CZY_ETAT_P2',
#     'P_CZY_ETAT_P3',
#     'P_CZY_ETAT_P4',
#     'P_CZY_ETAT_P5',
    
    'P_ME_ZAR',
    'P_ME_ZAR_P1',
    'P_ME_ZAR_P5',
   ]]

task_2_data["ZWROT_INWESTYCJI_ABSOLUTNY"] = task_2_data['P_ME_ZAR']/task_2_data['P_N_SEMESTR']
task_2_data["ZWROT_INWESTYCJI_SZYBKOSC"] = (task_2_data['P_ME_ZAR_P5'] - task_2_data['P_ME_ZAR_P1'])/task_2_data['P_N_SEMESTR']

task_2_data

,P_N,P_POZIOM,P_POZIOM_TEKST_PL,P_N_SEMESTR,P_NAZWA_UCZELNI,P_KIERUNEK_NAZWA,P_WWZ_MIES_60,P_E_ZAR_ETAT_P5,P_ZAR_ETAT_MAX,P_PROC_MIES_BEZR,P_PROC_MIES_BEZR_DOSW,P_WWB,P_ME_ZAR,P_ME_ZAR_P1,P_ME_ZAR_P5,ZWROT_INWESTYCJI_ABSOLUTNY,ZWROT_INWESTYCJI_SZYBKOSC
49,84,1,Studia pierwszego stopnia,9,Politechnika Poznańska,Informatyka,1.80,8455.20,14783.40,0.5,0.0,0.09,5582.42,3939.88,7689.11,620.268889,416.581111
52,35,2,Studia drugiego stopnia,3,Politechnika Wrocławska,Informatyka,2.67,12559.47,14779.35,1.0,0.0,0.14,7490.32,5986.47,12416.86,2496.773333,2143.463333
65,58,2,Studia drugiego stopnia,4,Uniwersytet Ekonomiczny w Krakowie,Informatyka i ekonometria,2.18,8168.58,19388.61,2.7,0.0,0.34,6404.01,3978.92,7751.39,1601.002500,943.117500
111,40,1,Studia pierwszego stopnia,6,Wyższa Szkoła Bankowa w Poznaniu,Informatyka i ekonometria,1.82,6083.71,18684.57,2.3,1.0,0.32,4514.63,3348.12,4910.88,752.438333,260.460000
137,127,2,Studia drugiego stopnia,3,Politechnika Śląska,Informatyka,1.84,8969.02,13587.34,0.6,0.0,0.11,6157.27,3973.81,8706.79,2052.423333,1577.660000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34699,26,2,Studia drugiego stopnia,3,Państwowa Wyższa Szkoła Informatyki i Przedsię...,Informatyka,NaN,NaN,12501.23,8.4,4.8,0.91,4319.43,3889.23,NaN,1439.810000,NaN
34742,47,1,Studia pierwszego stopnia,7,Politechnika Koszalińska,Informatyka,NaN,NaN,12169.70,3.1,1.7,0.81,3595.09,3160.98,NaN,513.584286,NaN
34813,42,2,Studia drugiego stopnia,4,Politechnika Wrocławska,Informatyka,NaN,NaN,15213.19,0.6,0.0,0.10,9113.31,8699.17,NaN,2278.327500,NaN
34815,51,2,Studia drugiego stopnia,4,Uniwersytet Ekonomiczny we Wrocławiu,Informatyka w biznesie - k. unikatowy,NaN,NaN,16062.08,0.4,0.0,0.16,6387.61,6594.70,NaN,1596.902500,NaN
34831,51,1,Studia pierwszego stopnia,7,Państwowa Wyższa Szkoła Zawodowa im. Stanisław...,Informatyka,NaN,NaN,5907.24,14.8,0.6,2.96,2713.56,2274.96,NaN,387.651429,NaN

In [8]:
import plotly.express as px
import plotly

graph_data = task_2_data[['P_ME_ZAR', 'P_KIERUNEK_NAZWA', 'P_NAZWA_UCZELNI', 'P_POZIOM']]

fig = px.scatter(
    graph_data, 
    x = 'P_ME_ZAR', 
    y = 'P_KIERUNEK_NAZWA',
    color = 'P_NAZWA_UCZELNI',
    facet_col = 'P_POZIOM', 
        
    title = "Zarobki na studiach informatycznych",

    labels={
        "P_ME_ZAR": "Średnie zarobki [PLN]",
        "P_KIERUNEK_NAZWA": "Kierunek",
        "P_NAZWA_UCZELNI": "Szkoła wyższa",
        "P_POZIOM": "Stopień studiów"
    }
)

plotly.offline.plot(fig, filename='Średnie_zarobki.html')

'Średnie_zarobki.html'

In [9]:
import plotly.express as px
import plotly

graph_data = task_2_data[['ZWROT_INWESTYCJI_ABSOLUTNY', 'P_KIERUNEK_NAZWA', 'P_NAZWA_UCZELNI', 'P_POZIOM']]

fig = px.scatter(
    graph_data, 
    x = 'ZWROT_INWESTYCJI_ABSOLUTNY', 
    y = 'P_KIERUNEK_NAZWA',
    color = 'P_NAZWA_UCZELNI',
    facet_col = 'P_POZIOM', 
    
    title = "Zwrot inwestycji (absolutny)",

    labels={
        "ZWROT_INWESTYCJI_ABSOLUTNY": "Średnie zarobki / liczba semestrów",
        "P_KIERUNEK_NAZWA": "Kierunek",
        "P_NAZWA_UCZELNI": "Szkoła wyższa",
        "P_POZIOM": "Stopień studiów"
    }
)

plotly.offline.plot(fig, filename='Zwrot_inwestycji_absolutny.html')

'Zwrot_inwestycji_absolutny.html'

In [10]:
import plotly.express as px
import plotly

graph_data = task_2_data[['ZWROT_INWESTYCJI_SZYBKOSC', 'P_KIERUNEK_NAZWA', 'P_NAZWA_UCZELNI', 'P_POZIOM']]

fig = px.scatter(
    graph_data, 
    x = 'ZWROT_INWESTYCJI_SZYBKOSC', 
    y = 'P_KIERUNEK_NAZWA',
    color = 'P_NAZWA_UCZELNI',
    facet_col = 'P_POZIOM', 

    title = "Zwrot inwestycji (szybkość)",
    
    labels={
        "ZWROT_INWESTYCJI_SZYBKOSC": "Wzrost zarobków z 1 do 5 roku po studiach / liczba semestrów",
        "P_KIERUNEK_NAZWA": "Kierunek",
        "P_NAZWA_UCZELNI": "Szkoła wyższa",
        "P_POZIOM": "Stopień studiów"
    }
)

plotly.offline.plot(fig, filename='Zwrot_inwestycji_szybkość.html')

'Zwrot_inwestycji_szybkość.html'

In [11]:
task_3_data = major_data.loc[
    (major_data["P_ROKDYP"] == 2014)
    & (major_data["P_POZIOM"] == "2")
    & (major_data["P_WOJ"] == 14)
]

task_3_data = task_3_data[[
    'P_DZIEDZINA',
    
    'P_ME_ZAR_P1',
    'P_ME_ZAR_P2',
    'P_ME_ZAR_P3',
    'P_ME_ZAR_P4',
    'P_ME_ZAR_P5']]

# task_3_data = task_3_data.set_index('P_DZIEDZINA').T
task_3_data

tmp = pd.DataFrame(columns=['P_DZIEDZINA', "PO_ROKU", 'P_ME_ZAR'])

for index, row in task_3_data.iterrows():
    row_to_append = pd.DataFrame([[str(row['P_DZIEDZINA']), 1, row['P_ME_ZAR_P1']]], columns=['P_DZIEDZINA', "PO_ROKU", 'P_ME_ZAR'])
    tmp = tmp.append(row_to_append, ignore_index=True)
    row_to_append = pd.DataFrame([[str(row['P_DZIEDZINA']), 2, row['P_ME_ZAR_P2']]], columns=['P_DZIEDZINA', "PO_ROKU", 'P_ME_ZAR'])
    tmp = tmp.append(row_to_append, ignore_index=True)
    row_to_append = pd.DataFrame([[str(row['P_DZIEDZINA']), 3, row['P_ME_ZAR_P3']]], columns=['P_DZIEDZINA', "PO_ROKU", 'P_ME_ZAR'])
    tmp = tmp.append(row_to_append, ignore_index=True)
    row_to_append = pd.DataFrame([[str(row['P_DZIEDZINA']), 4, row['P_ME_ZAR_P4']]], columns=['P_DZIEDZINA', "PO_ROKU", 'P_ME_ZAR'])
    tmp = tmp.append(row_to_append, ignore_index=True)
    row_to_append = pd.DataFrame([[str(row['P_DZIEDZINA']), 5, row['P_ME_ZAR_P5']]], columns=['P_DZIEDZINA', "PO_ROKU", 'P_ME_ZAR'])
    tmp = tmp.append(row_to_append, ignore_index=True)
    
task_3_data = tmp[tmp["P_DZIEDZINA"] != "nan"]

In [12]:
import plotly.express as px

fig = px.line(
    task_3_data, 
    x = 'PO_ROKU',
    y = 'P_ME_ZAR',
    color = 'P_DZIEDZINA',
    
    title = "Zarobki po ukończeniu studiów wedle dziedziny",
    
    labels={
        "PO_ROKU": "Po n latach od ukończenia",
        "P_ME_ZAR": "Średnie zarobki [PLN]",
        "P_DZIEDZINA": "Dziedzina nauki",
    }
)

plotly.offline.plot(fig, filename='Zarobki_dziedzina.html')

'Zarobki_dziedzina.html'

# ------------------------------------------------------------------------------------------------------

In [1]:
from datetime_periods import period

def date_within_period(date, start_date, end_date):
    return (date >= (start_date - timedelta(days=1)) and date <= (end_date + timedelta(days=1)))

def period_within_period(start_date_1, end_date_1, start_date_2, end_date_2):
    return date_within_period(start_date_1, start_date_2, end_date_2) and date_within_period(end_date_1, start_date_2, end_date_2)

def periods_overlap(start_date_1, end_date_1, start_date_2, end_date_2):
    return date_within_period(start_date_1, start_date_2, end_date_2) or date_within_period(end_date_1, start_date_2, end_date_2)

def add_periods(start_date_1, end_date_1, start_date_2, end_date_2):
    if period_within_period(start_date_1, end_date_1, start_date_2, end_date_2):
        return start_date_2, end_date_2
    if period_within_period(start_date_2, end_date_2, start_date_1, end_date_1):
        return start_date_1, end_date_1
    
    dates = [start_date_1, end_date_1, start_date_2, end_date_2]
    min_date = min(dates)
    
    return [min(dates), max(dates)]

def merge_period_into_periods(periods, start_date, end_date):
    if len(periods) == 0:
        periods.append([start_date, end_date])
        return periods
    
    added = False
    
    for period in periods:
        if period_within_period(start_date, end_date, period[0], period[1]):
            added = True
            break
        elif period_within_period(period[0], period[1], start_date, end_date):
            periods.remove(period)
            periods.append([start_date, end_date])
            added = True
            break
        elif periods_overlap(start_date, end_date, period[0], period[1]):
            periods.remove(period)
            periods.append(add_periods(start_date, end_date, period[0], period[1]))
            added = True
            break
    
    if not added:
        periods.append([start_date, end_date])
            
    return periods

In [13]:
import csv
from datetime import date, timedelta, datetime

tsv_file = open("export.tsv")
read_tsv = csv.reader(tsv_file, delimiter="\t")

active_periods_of_person = {}

firstline = True

index = 0
for row in read_tsv:
    if firstline:
        firstline = False
        continue
    
    index += 1
    if index % 1000 == 0:
        print("\r", "Processed", index, "records...", end='')
    
    student_id = row[0]
    course_id = row[1]
    
    start_date = datetime.strptime(row[2], '%y/%m/%d')
    if row[3] == '':
        end_date = datetime.today()
    else:
        end_date = datetime.strptime(row[3], '%y/%m/%d')
    
    if student_id not in active_periods_of_person.keys():
        active_periods_of_person[student_id] = {}
        
    if "courses" not in active_periods_of_person[student_id]:
         active_periods_of_person[student_id]["courses"] = {}
    
    if course_id not in active_periods_of_person[student_id]["courses"].keys():
        active_periods_of_person[student_id]["courses"][course_id] = []
        
    active_periods_of_person[student_id]["courses"][course_id] = merge_period_into_periods(
        active_periods_of_person[student_id]["courses"][course_id], 
        start_date, 
        end_date)

 Processed 500000 records...rocessed 75000 records...230000 records...Processed 253000 records...records...305000 records...Processed 320000 records...Processed 343000 records... records...records...records...

In [14]:
active_periods_of_person

{'1': {'courses': {'17484': [[datetime.datetime(2014, 10, 1, 0, 0),
     datetime.datetime(2020, 12, 18, 16, 53, 14, 950091)]],
   '4279': [[datetime.datetime(2014, 10, 1, 0, 0),
     datetime.datetime(2017, 12, 8, 0, 0)]],
   '1': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2012, 10, 24, 0, 0)]],
   '25514': [[datetime.datetime(2018, 10, 1, 0, 0),
     datetime.datetime(2020, 12, 18, 16, 53, 14, 950091)]],
   '10253': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 5, 0, 0)]],
   '14101': [[datetime.datetime(2018, 10, 1, 0, 0),
     datetime.datetime(2020, 12, 18, 16, 53, 14, 950091)]]}},
 '2': {'courses': {'465': [[datetime.datetime(2014, 2, 24, 0, 0),
     datetime.datetime(2015, 4, 22, 0, 0)]],
   '16412': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2014, 2, 23, 0, 0)]],
   '7007': [[datetime.datetime(2018, 12, 10, 0, 0),
     datetime.datetime(2019, 11, 19, 0, 0)],
    [datetime.datetime(2017, 7, 24, 0, 0),
     datetime.datetime(2018, 11, 23, 0, 0)]]}},
 '3': {'courses': {'20707': [[datetime.datetime(2018, 10, 1, 0, 0),
     datetime.datetime(2020, 12, 18, 16, 53, 14, 950091)]],
   '13118': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2015, 2, 20, 0, 0)]],
   '10846': [[datetime.datetime(2015, 3, 30, 0, 0),
     datetime.datetime(2016, 10, 13, 0, 0)]],
   '20161': [[datetime.datetime(2012, 10, 1, 0, 0),
     datetime.datetime(2018, 10, 31, 0, 0)]],
   '19626': [[datetime.datetime(2018, 10, 1, 0, 0),
     datetime.datetime(2020, 12, 18, 16, 53, 14, 950091)]]}},
 '4': {'courses': {'10313': [[datetime.datetime(2006, 8, 10, 0, 0),
     datetime.datetime(2011, 2, 2, 0, 0)]],
   '13120': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2012, 3, 2, 0, 0)]],
   '19683': [[datetime.datetime(2015, 9, 18, 0, 0),
     datetime.datetime(2015, 10, 16, 0, 0)],
    [datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2013, 9, 20, 0, 0)]]}},
 '5': {'courses': {'20198': [[datetime.datetime(2012, 10, 1, 0, 0),
     datetime.datetime(2014, 11, 20, 0, 0)]],
   '19686': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2013, 9, 25, 0, 0)]],
   '20976': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2012, 1, 30, 0, 0)]]}},
 '6': {'courses': {'13142': [[datetime.datetime(2011, 9, 27, 0, 0),
     datetime.datetime(2012, 3, 15, 0, 0)]],
   '3263': [[datetime.datetime(2009, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 1, 0, 0)]],
   '24215': [[datetime.datetime(2013, 9, 30, 0, 0),
     datetime.datetime(2015, 9, 10, 0, 0)]]}},
 '7': {'courses': {'22918': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2013, 9, 30, 0, 0)]],
   '13863': [[datetime.datetime(2013, 10, 1, 0, 0),
     datetime.datetime(2014, 1, 10, 0, 0)],
    [datetime.datetime(2016, 1, 26, 0, 0),
     datetime.datetime(2016, 6, 24, 0, 0)]]}},
 '8': {'courses': {'5': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2013, 7, 4, 0, 0)]]}},
 '9': {'courses': {'6531': [[datetime.datetime(2009, 10, 1, 0, 0),
     datetime.datetime(2013, 12, 16, 0, 0)]]}},
 '10': {'courses': {'281': [[datetime.datetime(2011, 10, 3, 0, 0),
     datetime.datetime(2012, 3, 16, 0, 0)]],
   '13121': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2015, 6, 9, 0, 0)]]}},
 '11': {'courses': {'3262': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 1, 0, 0)]],
   '10250': [[datetime.datetime(2013, 9, 28, 0, 0),
     datetime.datetime(2015, 7, 8, 0, 0)]]}},
 '12': {'courses': {'3262': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 9, 30, 0, 0)]]}},
 '13': {'courses': {'19682': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2015, 6, 24, 0, 0)]]}},
 '14': {'courses': {'13123': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2012, 11, 22, 0, 0)]],
   '18206': [[datetime.datetime(2013, 10, 1, 0, 0),
     datetime.datetime(2016, 7, 8, 0, 0)]],
   '24618': [[datetime.datetime(2016, 10, 1, 0, 0),
     datetime.datetime(2017, 11, 14, 0, 0)]]}},
 '15': {'courses': {'9813': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2013, 7, 5, 0, 0)]]}},
 '16': {'courses': {'16417': [[datetime.datetime(2011, 10, 4, 0, 0),
     datetime.datetime(2014, 7, 7, 0, 0)]],
   '20055': [[datetime.datetime(2014, 10, 1, 0, 0),
     datetime.datetime(2016, 7, 8, 0, 0)]]}},
 '17': {'courses': {'13703': [[datetime.datetime(2015, 10, 1, 0, 0),
     datetime.datetime(2017, 9, 20, 0, 0)]],
   '22922': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2012, 10, 16, 0, 0)]],
   '576': [[datetime.datetime(2012, 10, 23, 0, 0),
     datetime.datetime(2015, 7, 7, 0, 0)]]}},
 '18': {'courses': {'17741': [[datetime.datetime(2013, 9, 30, 0, 0),
     datetime.datetime(2015, 10, 14, 0, 0)]],
   '6532': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 1, 0, 0)]]}},
 '19': {'courses': {'17274': [[datetime.datetime(2013, 9, 30, 0, 0),
     datetime.datetime(2017, 10, 2, 0, 0)]],
   '12019': [[datetime.datetime(2018, 10, 1, 0, 0),
     datetime.datetime(2019, 4, 17, 0, 0)]],
   '16415': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 9, 13, 0, 0)]]}},
 '20': {'courses': {'9817': [[datetime.datetime(2011, 9, 19, 0, 0),
     datetime.datetime(2013, 7, 16, 0, 0)]]}},
 '21': {'courses': {'10431': [[datetime.datetime(2014, 10, 1, 0, 0),
     datetime.datetime(2020, 12, 18, 16, 53, 14, 951114)]],
   '13127': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 7, 7, 0, 0)]]}},
 '22': {'courses': {'14798': [[datetime.datetime(2015, 10, 1, 0, 0),
     datetime.datetime(2017, 6, 19, 0, 0)]],
   '16420': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2015, 6, 19, 0, 0)]]}},
 '23': {'courses': {'3263': [[datetime.datetime(2008, 10, 1, 0, 0),
     datetime.datetime(2015, 7, 6, 0, 0)]],
   '8701': [[datetime.datetime(2017, 10, 3, 0, 0),
     datetime.datetime(2018, 10, 1, 0, 0)]],
   '10301': [[datetime.datetime(2015, 12, 3, 0, 0),
     datetime.datetime(2017, 10, 2, 0, 0)]]}},
 '24': {'courses': {'3269': [[datetime.datetime(2011, 9, 24, 0, 0),
     datetime.datetime(2013, 3, 29, 0, 0)]],
   '1030': [[datetime.datetime(2009, 9, 28, 0, 0),
     datetime.datetime(2010, 3, 2, 0, 0)]]}},
 '25': {'courses': {'3270': [[datetime.datetime(2011, 10, 8, 0, 0),
     datetime.datetime(2013, 7, 1, 0, 0)]]}},
 '26': {'courses': {'3263': [[datetime.datetime(2007, 10, 1, 0, 0),
     datetime.datetime(2013, 10, 17, 0, 0)]],
   '9958': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2012, 2, 20, 0, 0)]],
   '17808': [[datetime.datetime(2013, 10, 1, 0, 0),
     datetime.datetime(2020, 12, 18, 16, 53, 14, 951114)]]}},
 '27': {'courses': {'19693': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 6, 28, 0, 0)]]}},
 '28': {'courses': {'10301': [[datetime.datetime(2013, 9, 30, 0, 0),
     datetime.datetime(2015, 7, 16, 0, 0)]],
   '3263': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 6, 28, 0, 0)]]}},
 '29': {'courses': {'19685': [[datetime.datetime(2011, 9, 19, 0, 0),
     datetime.datetime(2013, 9, 25, 0, 0)]]}},
 '30': {'courses': {'20430': [[datetime.datetime(2014, 10, 1, 0, 0),
     datetime.datetime(2016, 7, 5, 0, 0)]],
   '13127': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 6, 27, 0, 0)]]}},
 '31': {'courses': {'20777': [[datetime.datetime(2015, 2, 9, 0, 0),
     datetime.datetime(2017, 6, 30, 0, 0)]],
   '3263': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 10, 0, 0)]],
   '24215': [[datetime.datetime(2013, 9, 30, 0, 0),
     datetime.datetime(2015, 7, 7, 0, 0)]],
   '21638': [[datetime.datetime(2017, 12, 1, 0, 0),
     datetime.datetime(2019, 7, 5, 0, 0)]],
   '4793': [[datetime.datetime(2014, 10, 3, 0, 0),
     datetime.datetime(2015, 2, 19, 0, 0)]]}},
 '32': {'courses': {'19685': [[datetime.datetime(2011, 9, 19, 0, 0),
     datetime.datetime(2014, 2, 26, 0, 0)]],
   '941': [[datetime.datetime(2011, 9, 30, 0, 0),
     datetime.datetime(2014, 6, 10, 0, 0)]]}},
 '33': {'courses': {'13125': [[datetime.datetime(2011, 10, 15, 0, 0),
     datetime.datetime(2014, 10, 4, 0, 0)]]}},
 '34': {'courses': {'9815': [[datetime.datetime(2011, 9, 19, 0, 0),
     datetime.datetime(2014, 2, 25, 0, 0)]]}},
 '35': {'courses': {'3263': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2014, 6, 26, 0, 0)]],
   '24215': [[datetime.datetime(2014, 9, 29, 0, 0),
     datetime.datetime(2017, 10, 2, 0, 0)]]}},
 '36': {'courses': {'16421': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 5, 0, 0)]],
   '3525': [[datetime.datetime(2009, 10, 5, 0, 0),
     datetime.datetime(2012, 11, 25, 0, 0)]],
   '11532': [[datetime.datetime(2013, 10, 1, 0, 0),
     datetime.datetime(2015, 7, 5, 0, 0)]]}},
 '37': {'courses': {'6530': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 11, 0, 0)]]}},
 '38': {'courses': {'13502': [[datetime.datetime(2014, 10, 1, 0, 0),
     datetime.datetime(2016, 7, 6, 0, 0)]],
   '22927': [[datetime.datetime(2011, 8, 22, 0, 0),
     datetime.datetime(2014, 7, 10, 0, 0)]]}},
 '39': {'courses': {'982': [[datetime.datetime(2016, 7, 7, 0, 0),
     datetime.datetime(2016, 7, 7, 0, 0)]],
   '22928': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2014, 8, 20, 0, 0)]]}},
 '40': {'courses': {'22927': [[datetime.datetime(2011, 8, 22, 0, 0),
     datetime.datetime(2014, 11, 7, 0, 0)]]}},
 '41': {'courses': {'22920': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 7, 0, 0)]]}},
 '42': {'courses': {'6530': [[datetime.datetime(2011, 10, 3, 0, 0),
     datetime.datetime(2014, 1, 21, 0, 0)]]}},
 '43': {'courses': {'23949': [[datetime.datetime(2013, 10, 1, 0, 0),
     datetime.datetime(2015, 7, 14, 0, 0)]],
   '9821': [[datetime.datetime(2010, 9, 27, 0, 0),
     datetime.datetime(2013, 7, 10, 0, 0)]]}},
 '44': {'courses': {'22928': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2014, 7, 10, 0, 0)]],
   '14117': [[datetime.datetime(2014, 10, 1, 0, 0),
     datetime.datetime(2016, 7, 7, 0, 0)]]}},
 '45': {'courses': {'6530': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 6, 0, 0)]]}},
 '46': {'courses': {'24215': [[datetime.datetime(2014, 11, 14, 0, 0),
     datetime.datetime(2017, 10, 2, 0, 0)]],
   '3263': [[datetime.datetime(2009, 10, 1, 0, 0),
     datetime.datetime(2014, 10, 20, 0, 0)]]}},
 '47': {'courses': {'9817': [[datetime.datetime(2011, 9, 19, 0, 0),
     datetime.datetime(2013, 4, 22, 0, 0)]]}},
 '48': {'courses': {'22927': [[datetime.datetime(2011, 8, 22, 0, 0),
     datetime.datetime(2014, 7, 10, 0, 0)]],
   '17149': [[datetime.datetime(2014, 10, 11, 0, 0),
     datetime.datetime(2016, 6, 22, 0, 0)]]}},
 '49': {'courses': {'22925': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 9, 10, 0, 0)]]}},
 '50': {'courses': {'9817': [[datetime.datetime(2011, 9, 19, 0, 0),
     datetime.datetime(2013, 7, 1, 0, 0)]]}},
 '51': {'courses': {'13132': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 7, 4, 0, 0)]]}},
 '52': {'courses': {'13127': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 11, 27, 0, 0)]]}},
 '53': {'courses': {'19689': [[datetime.datetime(2010, 9, 29, 0, 0),
     datetime.datetime(2013, 6, 25, 0, 0)]]}},
 '54': {'courses': {'9817': [[datetime.datetime(2011, 9, 19, 0, 0),
     datetime.datetime(2013, 10, 17, 0, 0)]]}},
 '55': {'courses': {'9822': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 6, 27, 0, 0)]]}},
 '56': {'courses': {'14948': [[datetime.datetime(2014, 10, 18, 0, 0),
     datetime.datetime(2016, 7, 8, 0, 0)]],
   '13125': [[datetime.datetime(2011, 10, 15, 0, 0),
     datetime.datetime(2014, 9, 12, 0, 0)]]}},
 '57': {'courses': {'2576': [[datetime.datetime(2019, 10, 1, 0, 0),
     datetime.datetime(2020, 12, 18, 16, 53, 14, 952084)]],
   '13127': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 7, 7, 0, 0)]]}},
 '58': {'courses': {'6531': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 9, 17, 0, 0)]],
   '688': [[datetime.datetime(2015, 10, 1, 0, 0),
     datetime.datetime(2015, 12, 2, 0, 0)]]}},
 '59': {'courses': {'9817': [[datetime.datetime(2011, 9, 19, 0, 0),
     datetime.datetime(2013, 12, 19, 0, 0)]]}},
 '60': {'courses': {'9817': [[datetime.datetime(2011, 9, 19, 0, 0),
     datetime.datetime(2016, 12, 1, 0, 0)]]}},
 '61': {'courses': {'9817': [[datetime.datetime(2011, 9, 19, 0, 0),
     datetime.datetime(2013, 10, 17, 0, 0)]],
   '10169': [[datetime.datetime(2008, 10, 1, 0, 0),
     datetime.datetime(2011, 6, 28, 0, 0)]]}},
 '62': {'courses': {'19685': [[datetime.datetime(2011, 9, 19, 0, 0),
     datetime.datetime(2013, 9, 27, 0, 0)]],
   '24215': [[datetime.datetime(2013, 9, 30, 0, 0),
     datetime.datetime(2017, 10, 1, 0, 0)]],
   '7003': [[datetime.datetime(2012, 10, 1, 0, 0),
     datetime.datetime(2012, 12, 18, 0, 0)]],
   '11987': [[datetime.datetime(2017, 10, 1, 0, 0),
     datetime.datetime(2018, 7, 17, 0, 0)]]}},
 '63': {'courses': {'19691': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2013, 6, 4, 0, 0)]]}},
 '64': {'courses': {'13135': [[datetime.datetime(2011, 10, 3, 0, 0),
     datetime.datetime(2013, 9, 30, 0, 0)]]}},
 '65': {'courses': {'22925': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 7, 2, 0, 0)]]}},
 '66': {'courses': {'13128': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2013, 6, 13, 0, 0)]]}},
 '67': {'courses': {'19685': [[datetime.datetime(2011, 9, 19, 0, 0),
     datetime.datetime(2013, 7, 23, 0, 0)]]}},
 '68': {'courses': {'16425': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 6, 13, 0, 0)]],
   '20797': [[datetime.datetime(2014, 10, 1, 0, 0),
     datetime.datetime(2016, 6, 20, 0, 0)]]}},
 '69': {'courses': {'6989': [[datetime.datetime(2014, 10, 1, 0, 0),
     datetime.datetime(2017, 9, 29, 0, 0)]],
   '16425': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 6, 3, 0, 0)]]}},
 '70': {'courses': {'16428': [[datetime.datetime(2009, 9, 26, 0, 0),
     datetime.datetime(2015, 1, 2, 0, 0)]]}},
 '71': {'courses': {'13135': [[datetime.datetime(2011, 10, 3, 0, 0),
     datetime.datetime(2013, 9, 7, 0, 0)]]}},
 '72': {'courses': {'13135': [[datetime.datetime(2011, 10, 3, 0, 0),
     datetime.datetime(2013, 7, 5, 0, 0)]]}},
 '73': {'courses': {'3263': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 9, 12, 0, 0)]],
   '1291': [[datetime.datetime(2019, 10, 5, 0, 0),
     datetime.datetime(2020, 12, 18, 16, 53, 14, 952084)]]}},
 '74': {'courses': {'4622': [[datetime.datetime(2013, 9, 30, 0, 0),
     datetime.datetime(2015, 6, 17, 0, 0)]],
   '14': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 12, 0, 0)]]}},
 '75': {'courses': {'1703': [[datetime.datetime(2015, 9, 30, 0, 0),
     datetime.datetime(2019, 9, 27, 0, 0)]],
   '3055': [[datetime.datetime(2019, 10, 1, 0, 0),
     datetime.datetime(2019, 12, 7, 0, 0)]],
   '13126': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 8, 0, 0)]]}},
 '76': {'courses': {'20797': [[datetime.datetime(2014, 10, 1, 0, 0),
     datetime.datetime(2016, 6, 6, 0, 0)]],
   '16425': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 6, 16, 0, 0)]]}},
 '77': {'courses': {'13135': [[datetime.datetime(2011, 10, 3, 0, 0),
     datetime.datetime(2014, 1, 16, 0, 0)]],
   '10799': [[datetime.datetime(2017, 3, 4, 0, 0),
     datetime.datetime(2017, 9, 14, 0, 0)]]}},
 '78': {'courses': {'4622': [[datetime.datetime(2013, 9, 30, 0, 0),
     datetime.datetime(2015, 6, 30, 0, 0)]],
   '16861': [[datetime.datetime(2013, 9, 30, 0, 0),
     datetime.datetime(2013, 11, 29, 0, 0)]],
   '14': [[datetime.datetime(2011, 10, 18, 0, 0),
     datetime.datetime(2013, 7, 12, 0, 0)]]}},
 '79': {'courses': {'7533': [[datetime.datetime(2015, 10, 1, 0, 0),
     datetime.datetime(2018, 10, 30, 0, 0)]],
   '21436': [[datetime.datetime(2017, 10, 1, 0, 0),
     datetime.datetime(2018, 11, 17, 0, 0)]],
   '16420': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2015, 6, 19, 0, 0)]]}},
 '80': {'courses': {'6544': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2013, 12, 21, 0, 0)]]}},
 '81': {'courses': {'6544': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 7, 4, 0, 0)]]}},
 '82': {'courses': {'9823': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2013, 10, 12, 0, 0)]]}},
 '83': {'courses': {'13139': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 9, 30, 0, 0)]],
   '1154': [[datetime.datetime(2015, 3, 1, 0, 0),
     datetime.datetime(2015, 9, 30, 0, 0)]]}},
 '84': {'courses': {'6544': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 4, 0, 0)]]}},
 '85': {'courses': {'3277': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 5, 0, 0)]],
   '13513': [[datetime.datetime(2013, 10, 1, 0, 0),
     datetime.datetime(2015, 7, 3, 0, 0)]]}},
 '86': {'courses': {'22935': [[datetime.datetime(2009, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 31, 0, 0)]]}},
 '87': {'courses': {'13513': [[datetime.datetime(2013, 10, 1, 0, 0),
     datetime.datetime(2015, 7, 9, 0, 0)]],
   '20': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 6, 0, 0)]]}},
 '88': {'courses': {'13139': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 10, 3, 0, 0)]],
   '14300': [[datetime.datetime(2014, 10, 1, 0, 0),
     datetime.datetime(2016, 10, 29, 0, 0)]]}},
 '89': {'courses': {'9823': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 2, 0, 0)]]}},
 '90': {'courses': {'13513': [[datetime.datetime(2013, 10, 1, 0, 0),
     datetime.datetime(2015, 7, 10, 0, 0)]],
   '22935': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 1, 0, 0)]]}},
 '91': {'courses': {'3277': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 7, 2, 0, 0)]],
   '13513': [[datetime.datetime(2014, 10, 1, 0, 0),
     datetime.datetime(2016, 9, 24, 0, 0)]]}},
 '92': {'courses': {'9823': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 8, 0, 0)]]}},
 '93': {'courses': {'22938': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 6, 12, 0, 0)]],
   '17858': [[datetime.datetime(2014, 10, 1, 0, 0),
     datetime.datetime(2016, 6, 22, 0, 0)]]}},
 '94': {'courses': {'19702': [[datetime.datetime(2011, 10, 8, 0, 0),
     datetime.datetime(2014, 2, 14, 0, 0)]]}},
 '95': {'courses': {'13130': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2020, 12, 18, 16, 53, 14, 953082)]]}},
 '96': {'courses': {'9815': [[datetime.datetime(2011, 9, 19, 0, 0),
     datetime.datetime(2015, 5, 28, 0, 0)]]}},
 '97': {'courses': {'5204': [[datetime.datetime(2014, 11, 21, 0, 0),
     datetime.datetime(2014, 11, 21, 0, 0)]],
   '16423': [[datetime.datetime(2011, 9, 15, 0, 0),
     datetime.datetime(2013, 8, 19, 0, 0)]]}},
 '98': {'courses': {'22927': [[datetime.datetime(2011, 8, 22, 0, 0),
     datetime.datetime(2013, 4, 10, 0, 0)]]}},
 '99': {'courses': {'1918': [[datetime.datetime(2014, 10, 1, 0, 0),
     datetime.datetime(2016, 7, 8, 0, 0)]],
   '22938': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 6, 12, 0, 0)]]}},
 '100': {'courses': {'6532': [[datetime.datetime(2011, 9, 19, 0, 0),
     datetime.datetime(2014, 6, 27, 0, 0)]],
   '17741': [[datetime.datetime(2014, 9, 29, 0, 0),
     datetime.datetime(2016, 7, 14, 0, 0)]]}},
 '101': {'courses': {'13130': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2013, 6, 30, 0, 0)]],
   '3796': [[datetime.datetime(2014, 10, 1, 0, 0),
     datetime.datetime(2016, 7, 3, 0, 0)]]}},
 '102': {'courses': {'1482': [[datetime.datetime(2014, 10, 1, 0, 0),
     datetime.datetime(2014, 12, 10, 0, 0)]],

In [15]:
def merge_periods(periods):
    if len(periods) == 0:
        return periods
    
    periods = [list(x) for x in {(tuple(e)) for e in periods}]
    
    old_periods = []
    merged_periods = []
    while old_periods != periods:
        old_periods = periods
        for period in periods:
            tmp_periods = periods
            merged_periods = merge_period_into_periods(tmp_periods, period[0], period[1])
        
        periods = merged_periods
        
    return periods

# https://stackoverflow.com/a/48754702
def count_months(start_date,end_date):
    qty_month = ((end_date.year - start_date.year) * 12) + (end_date.month - start_date.month)

    d_days = end_date.day - start_date.day

    if d_days >= 0:
        adjust = 0
    else:
        adjust = -1
    qty_month += adjust

    return qty_month

In [16]:
for student_id, course_periods in active_periods_of_person.items():
    for course_id, periods in active_periods_of_person[student_id]["courses"].items():
        periods = merge_periods(periods)
    
for student_id, data in active_periods_of_person.items():
    active_periods_of_person[student_id]["All courses periods"] = []    
    for course_id, periods in active_periods_of_person[student_id]["courses"].items():
        active_periods_of_person[student_id]["All courses periods"] += periods

    active_periods_of_person[student_id]["All courses periods"] = merge_periods(active_periods_of_person[student_id]["All courses periods"])
    
    student_months_total = 0
    for period in active_periods_of_person[student_id]["All courses periods"]:
        student_months_total += count_months(period[0], period[1])
    
    active_periods_of_person[student_id]["Total months"] = student_months_total

active_periods_of_person

{'1': {'courses': {'17484': [[datetime.datetime(2014, 10, 1, 0, 0),
     datetime.datetime(2020, 12, 18, 16, 53, 14, 950091)]],
   '4279': [[datetime.datetime(2014, 10, 1, 0, 0),
     datetime.datetime(2017, 12, 8, 0, 0)]],
   '1': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2012, 10, 24, 0, 0)]],
   '25514': [[datetime.datetime(2018, 10, 1, 0, 0),
     datetime.datetime(2020, 12, 18, 16, 53, 14, 950091)]],
   '10253': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 5, 0, 0)]],
   '14101': [[datetime.datetime(2018, 10, 1, 0, 0),
     datetime.datetime(2020, 12, 18, 16, 53, 14, 950091)]]},
  'All courses periods': [[datetime.datetime(2014, 10, 1, 0, 0),
    datetime.datetime(2020, 12, 18, 16, 53, 14, 950091)],
   [datetime.datetime(2018, 10, 1, 0, 0),
    datetime.datetime(2020, 12, 18, 16, 53, 14, 950091)],
   [datetime.datetime(2014, 10, 1, 0, 0),
    datetime.datetime(2017, 12, 8, 0, 0)],
   [datetime.datetime(2010, 10, 1, 0, 0), datetime.datetime(2013, 7, 5, 0, 0)],
   [datetime.datetime(2010, 10, 1, 0, 0),
    datetime.datetime(2013, 7, 5, 0, 0)]],
  'Total months': 204},
 '2': {'courses': {'465': [[datetime.datetime(2014, 2, 24, 0, 0),
     datetime.datetime(2015, 4, 22, 0, 0)]],
   '16412': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2014, 2, 23, 0, 0)]],
   '7007': [[datetime.datetime(2018, 12, 10, 0, 0),
     datetime.datetime(2019, 11, 19, 0, 0)],
    [datetime.datetime(2017, 7, 24, 0, 0),
     datetime.datetime(2018, 11, 23, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2018, 12, 10, 0, 0),
    datetime.datetime(2019, 11, 19, 0, 0)],
   [datetime.datetime(2017, 7, 24, 0, 0),
    datetime.datetime(2018, 11, 23, 0, 0)],
   [datetime.datetime(2011, 9, 26, 0, 0),
    datetime.datetime(2015, 4, 22, 0, 0)],
   [datetime.datetime(2011, 9, 26, 0, 0),
    datetime.datetime(2015, 4, 22, 0, 0)]],
  'Total months': 110},
 '3': {'courses': {'20707': [[datetime.datetime(2018, 10, 1, 0, 0),
     datetime.datetime(2020, 12, 18, 16, 53, 14, 950091)]],
   '13118': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2015, 2, 20, 0, 0)]],
   '10846': [[datetime.datetime(2015, 3, 30, 0, 0),
     datetime.datetime(2016, 10, 13, 0, 0)]],
   '20161': [[datetime.datetime(2012, 10, 1, 0, 0),
     datetime.datetime(2018, 10, 31, 0, 0)]],
   '19626': [[datetime.datetime(2018, 10, 1, 0, 0),
     datetime.datetime(2020, 12, 18, 16, 53, 14, 950091)]]},
  'All courses periods': [[datetime.datetime(2018, 10, 1, 0, 0),
    datetime.datetime(2020, 12, 18, 16, 53, 14, 950091)],
   [datetime.datetime(2011, 9, 26, 0, 0),
    datetime.datetime(2015, 2, 20, 0, 0)],
   [datetime.datetime(2012, 10, 1, 0, 0),
    datetime.datetime(2018, 10, 31, 0, 0)],
   [datetime.datetime(2012, 10, 1, 0, 0),
    datetime.datetime(2018, 10, 31, 0, 0)]],
  'Total months': 210},
 '4': {'courses': {'10313': [[datetime.datetime(2006, 8, 10, 0, 0),
     datetime.datetime(2011, 2, 2, 0, 0)]],
   '13120': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2012, 3, 2, 0, 0)]],
   '19683': [[datetime.datetime(2015, 9, 18, 0, 0),
     datetime.datetime(2015, 10, 16, 0, 0)],
    [datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2013, 9, 20, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2015, 9, 18, 0, 0),
    datetime.datetime(2015, 10, 16, 0, 0)],
   [datetime.datetime(2011, 9, 26, 0, 0),
    datetime.datetime(2013, 9, 20, 0, 0)],
   [datetime.datetime(2006, 8, 10, 0, 0), datetime.datetime(2011, 2, 2, 0, 0)],
   [datetime.datetime(2011, 9, 26, 0, 0),
    datetime.datetime(2013, 9, 20, 0, 0)]],
  'Total months': 99},
 '5': {'courses': {'20198': [[datetime.datetime(2012, 10, 1, 0, 0),
     datetime.datetime(2014, 11, 20, 0, 0)]],
   '19686': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2013, 9, 25, 0, 0)]],
   '20976': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2012, 1, 30, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2011, 10, 1, 0, 0),
    datetime.datetime(2012, 1, 30, 0, 0)],
   [datetime.datetime(2011, 9, 26, 0, 0),
    datetime.datetime(2014, 11, 20, 0, 0)],
   [datetime.datetime(2011, 9, 26, 0, 0),
    datetime.datetime(2014, 11, 20, 0, 0)]],
  'Total months': 77},
 '6': {'courses': {'13142': [[datetime.datetime(2011, 9, 27, 0, 0),
     datetime.datetime(2012, 3, 15, 0, 0)]],
   '3263': [[datetime.datetime(2009, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 1, 0, 0)]],
   '24215': [[datetime.datetime(2013, 9, 30, 0, 0),
     datetime.datetime(2015, 9, 10, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2009, 10, 1, 0, 0),
    datetime.datetime(2013, 7, 1, 0, 0)],
   [datetime.datetime(2013, 9, 30, 0, 0),
    datetime.datetime(2015, 9, 10, 0, 0)],
   [datetime.datetime(2009, 10, 1, 0, 0),
    datetime.datetime(2013, 7, 1, 0, 0)]],
  'Total months': 113},
 '7': {'courses': {'22918': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2013, 9, 30, 0, 0)]],
   '13863': [[datetime.datetime(2013, 10, 1, 0, 0),
     datetime.datetime(2014, 1, 10, 0, 0)],
    [datetime.datetime(2016, 1, 26, 0, 0),
     datetime.datetime(2016, 6, 24, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2016, 1, 26, 0, 0),
    datetime.datetime(2016, 6, 24, 0, 0)],
   [datetime.datetime(2013, 10, 1, 0, 0),
    datetime.datetime(2014, 1, 10, 0, 0)],
   [datetime.datetime(2011, 9, 26, 0, 0),
    datetime.datetime(2014, 1, 10, 0, 0)]],
  'Total months': 34},
 '8': {'courses': {'5': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2013, 7, 4, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2011, 9, 26, 0, 0),
    datetime.datetime(2013, 7, 4, 0, 0)]],
  'Total months': 21},
 '9': {'courses': {'6531': [[datetime.datetime(2009, 10, 1, 0, 0),
     datetime.datetime(2013, 12, 16, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2009, 10, 1, 0, 0),
    datetime.datetime(2013, 12, 16, 0, 0)]],
  'Total months': 50},
 '10': {'courses': {'281': [[datetime.datetime(2011, 10, 3, 0, 0),
     datetime.datetime(2012, 3, 16, 0, 0)]],
   '13121': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2015, 6, 9, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2011, 9, 26, 0, 0),
    datetime.datetime(2015, 6, 9, 0, 0)],
   [datetime.datetime(2011, 10, 3, 0, 0),
    datetime.datetime(2012, 3, 16, 0, 0)]],
  'Total months': 49},
 '11': {'courses': {'3262': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 1, 0, 0)]],
   '10250': [[datetime.datetime(2013, 9, 28, 0, 0),
     datetime.datetime(2015, 7, 8, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2013, 9, 28, 0, 0),
    datetime.datetime(2015, 7, 8, 0, 0)],
   [datetime.datetime(2010, 10, 1, 0, 0),
    datetime.datetime(2013, 7, 1, 0, 0)]],
  'Total months': 54},
 '12': {'courses': {'3262': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 9, 30, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2010, 10, 1, 0, 0),
    datetime.datetime(2013, 9, 30, 0, 0)]],
  'Total months': 35},
 '13': {'courses': {'19682': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2015, 6, 24, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2011, 9, 26, 0, 0),
    datetime.datetime(2015, 6, 24, 0, 0)]],
  'Total months': 44},
 '14': {'courses': {'13123': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2012, 11, 22, 0, 0)]],
   '18206': [[datetime.datetime(2013, 10, 1, 0, 0),
     datetime.datetime(2016, 7, 8, 0, 0)]],
   '24618': [[datetime.datetime(2016, 10, 1, 0, 0),
     datetime.datetime(2017, 11, 14, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2013, 10, 1, 0, 0),
    datetime.datetime(2016, 7, 8, 0, 0)],
   [datetime.datetime(2016, 10, 1, 0, 0),
    datetime.datetime(2017, 11, 14, 0, 0)],
   [datetime.datetime(2011, 9, 26, 0, 0),
    datetime.datetime(2012, 11, 22, 0, 0)]],
  'Total months': 59},
 '15': {'courses': {'9813': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2013, 7, 5, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2011, 9, 26, 0, 0),
    datetime.datetime(2013, 7, 5, 0, 0)]],
  'Total months': 21},
 '16': {'courses': {'16417': [[datetime.datetime(2011, 10, 4, 0, 0),
     datetime.datetime(2014, 7, 7, 0, 0)]],
   '20055': [[datetime.datetime(2014, 10, 1, 0, 0),
     datetime.datetime(2016, 7, 8, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2011, 10, 4, 0, 0),
    datetime.datetime(2014, 7, 7, 0, 0)],
   [datetime.datetime(2014, 10, 1, 0, 0),
    datetime.datetime(2016, 7, 8, 0, 0)]],
  'Total months': 54},
 '17': {'courses': {'13703': [[datetime.datetime(2015, 10, 1, 0, 0),
     datetime.datetime(2017, 9, 20, 0, 0)]],
   '22922': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2012, 10, 16, 0, 0)]],
   '576': [[datetime.datetime(2012, 10, 23, 0, 0),
     datetime.datetime(2015, 7, 7, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2015, 10, 1, 0, 0),
    datetime.datetime(2017, 9, 20, 0, 0)],
   [datetime.datetime(2012, 10, 23, 0, 0),
    datetime.datetime(2015, 7, 7, 0, 0)],
   [datetime.datetime(2011, 10, 1, 0, 0),
    datetime.datetime(2012, 10, 16, 0, 0)]],
  'Total months': 67},
 '18': {'courses': {'17741': [[datetime.datetime(2013, 9, 30, 0, 0),
     datetime.datetime(2015, 10, 14, 0, 0)]],
   '6532': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 1, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2013, 9, 30, 0, 0),
    datetime.datetime(2015, 10, 14, 0, 0)],
   [datetime.datetime(2010, 10, 1, 0, 0),
    datetime.datetime(2013, 7, 1, 0, 0)]],
  'Total months': 57},
 '19': {'courses': {'17274': [[datetime.datetime(2013, 9, 30, 0, 0),
     datetime.datetime(2017, 10, 2, 0, 0)]],
   '12019': [[datetime.datetime(2018, 10, 1, 0, 0),
     datetime.datetime(2019, 4, 17, 0, 0)]],
   '16415': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 9, 13, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2010, 10, 1, 0, 0),
    datetime.datetime(2013, 9, 13, 0, 0)],
   [datetime.datetime(2013, 9, 30, 0, 0),
    datetime.datetime(2017, 10, 2, 0, 0)],
   [datetime.datetime(2018, 10, 1, 0, 0),
    datetime.datetime(2019, 4, 17, 0, 0)]],
  'Total months': 89},
 '20': {'courses': {'9817': [[datetime.datetime(2011, 9, 19, 0, 0),
     datetime.datetime(2013, 7, 16, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2011, 9, 19, 0, 0),
    datetime.datetime(2013, 7, 16, 0, 0)]],
  'Total months': 21},
 '21': {'courses': {'10431': [[datetime.datetime(2014, 10, 1, 0, 0),
     datetime.datetime(2020, 12, 18, 16, 53, 14, 951114)]],
   '13127': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 7, 7, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2011, 10, 1, 0, 0),
    datetime.datetime(2014, 7, 7, 0, 0)],
   [datetime.datetime(2014, 10, 1, 0, 0),
    datetime.datetime(2020, 12, 18, 16, 53, 14, 951114)]],
  'Total months': 107},
 '22': {'courses': {'14798': [[datetime.datetime(2015, 10, 1, 0, 0),
     datetime.datetime(2017, 6, 19, 0, 0)]],
   '16420': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2015, 6, 19, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2011, 10, 1, 0, 0),
    datetime.datetime(2015, 6, 19, 0, 0)],
   [datetime.datetime(2015, 10, 1, 0, 0),
    datetime.datetime(2017, 6, 19, 0, 0)]],
  'Total months': 64},
 '23': {'courses': {'3263': [[datetime.datetime(2008, 10, 1, 0, 0),
     datetime.datetime(2015, 7, 6, 0, 0)]],
   '8701': [[datetime.datetime(2017, 10, 3, 0, 0),
     datetime.datetime(2018, 10, 1, 0, 0)]],
   '10301': [[datetime.datetime(2015, 12, 3, 0, 0),
     datetime.datetime(2017, 10, 2, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2008, 10, 1, 0, 0),
    datetime.datetime(2015, 7, 6, 0, 0)],
   [datetime.datetime(2015, 12, 3, 0, 0),
    datetime.datetime(2017, 10, 2, 0, 0)],
   [datetime.datetime(2015, 12, 3, 0, 0),
    datetime.datetime(2018, 10, 1, 0, 0)]],
  'Total months': 135},
 '24': {'courses': {'3269': [[datetime.datetime(2011, 9, 24, 0, 0),
     datetime.datetime(2013, 3, 29, 0, 0)]],
   '1030': [[datetime.datetime(2009, 9, 28, 0, 0),
     datetime.datetime(2010, 3, 2, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2009, 9, 28, 0, 0),
    datetime.datetime(2010, 3, 2, 0, 0)],
   [datetime.datetime(2011, 9, 24, 0, 0),
    datetime.datetime(2013, 3, 29, 0, 0)]],
  'Total months': 23},
 '25': {'courses': {'3270': [[datetime.datetime(2011, 10, 8, 0, 0),
     datetime.datetime(2013, 7, 1, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2011, 10, 8, 0, 0),
    datetime.datetime(2013, 7, 1, 0, 0)]],
  'Total months': 20},
 '26': {'courses': {'3263': [[datetime.datetime(2007, 10, 1, 0, 0),
     datetime.datetime(2013, 10, 17, 0, 0)]],
   '9958': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2012, 2, 20, 0, 0)]],
   '17808': [[datetime.datetime(2013, 10, 1, 0, 0),
     datetime.datetime(2020, 12, 18, 16, 53, 14, 951114)]]},
  'All courses periods': [[datetime.datetime(2011, 10, 1, 0, 0),
    datetime.datetime(2012, 2, 20, 0, 0)],
   [datetime.datetime(2013, 10, 1, 0, 0),
    datetime.datetime(2020, 12, 18, 16, 53, 14, 951114)],
   [datetime.datetime(2007, 10, 1, 0, 0),
    datetime.datetime(2020, 12, 18, 16, 53, 14, 951114)]],
  'Total months': 248},
 '27': {'courses': {'19693': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 6, 28, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2011, 10, 1, 0, 0),
    datetime.datetime(2014, 6, 28, 0, 0)]],
  'Total months': 32},
 '28': {'courses': {'10301': [[datetime.datetime(2013, 9, 30, 0, 0),
     datetime.datetime(2015, 7, 16, 0, 0)]],
   '3263': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 6, 28, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2013, 9, 30, 0, 0),
    datetime.datetime(2015, 7, 16, 0, 0)],
   [datetime.datetime(2010, 10, 1, 0, 0),
    datetime.datetime(2013, 6, 28, 0, 0)]],
  'Total months': 53},
 '29': {'courses': {'19685': [[datetime.datetime(2011, 9, 19, 0, 0),
     datetime.datetime(2013, 9, 25, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2011, 9, 19, 0, 0),
    datetime.datetime(2013, 9, 25, 0, 0)]],
  'Total months': 24},
 '30': {'courses': {'20430': [[datetime.datetime(2014, 10, 1, 0, 0),
     datetime.datetime(2016, 7, 5, 0, 0)]],
   '13127': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 6, 27, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2014, 10, 1, 0, 0),
    datetime.datetime(2016, 7, 5, 0, 0)],
   [datetime.datetime(2011, 10, 1, 0, 0),
    datetime.datetime(2014, 6, 27, 0, 0)]],
  'Total months': 53},
 '31': {'courses': {'20777': [[datetime.datetime(2015, 2, 9, 0, 0),
     datetime.datetime(2017, 6, 30, 0, 0)]],
   '3263': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 10, 0, 0)]],
   '24215': [[datetime.datetime(2013, 9, 30, 0, 0),
     datetime.datetime(2015, 7, 7, 0, 0)]],
   '21638': [[datetime.datetime(2017, 12, 1, 0, 0),
     datetime.datetime(2019, 7, 5, 0, 0)]],
   '4793': [[datetime.datetime(2014, 10, 3, 0, 0),
     datetime.datetime(2015, 2, 19, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2010, 10, 1, 0, 0),
    datetime.datetime(2013, 7, 10, 0, 0)],
   [datetime.datetime(2017, 12, 1, 0, 0), datetime.datetime(2019, 7, 5, 0, 0)],
   [datetime.datetime(2014, 10, 3, 0, 0),
    datetime.datetime(2017, 6, 30, 0, 0)],
   [datetime.datetime(2013, 9, 30, 0, 0),
    datetime.datetime(2017, 6, 30, 0, 0)],
   [datetime.datetime(2013, 9, 30, 0, 0),
    datetime.datetime(2017, 6, 30, 0, 0)]],
  'Total months': 174},
 '32': {'courses': {'19685': [[datetime.datetime(2011, 9, 19, 0, 0),
     datetime.datetime(2014, 2, 26, 0, 0)]],
   '941': [[datetime.datetime(2011, 9, 30, 0, 0),
     datetime.datetime(2014, 6, 10, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2011, 9, 30, 0, 0),
    datetime.datetime(2014, 6, 10, 0, 0)],
   [datetime.datetime(2011, 9, 19, 0, 0),
    datetime.datetime(2014, 6, 10, 0, 0)]],
  'Total months': 64},
 '33': {'courses': {'13125': [[datetime.datetime(2011, 10, 15, 0, 0),
     datetime.datetime(2014, 10, 4, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2011, 10, 15, 0, 0),
    datetime.datetime(2014, 10, 4, 0, 0)]],
  'Total months': 35},
 '34': {'courses': {'9815': [[datetime.datetime(2011, 9, 19, 0, 0),
     datetime.datetime(2014, 2, 25, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2011, 9, 19, 0, 0),
    datetime.datetime(2014, 2, 25, 0, 0)]],
  'Total months': 29},
 '35': {'courses': {'3263': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2014, 6, 26, 0, 0)]],
   '24215': [[datetime.datetime(2014, 9, 29, 0, 0),
     datetime.datetime(2017, 10, 2, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2010, 10, 1, 0, 0),
    datetime.datetime(2014, 6, 26, 0, 0)],
   [datetime.datetime(2014, 9, 29, 0, 0),
    datetime.datetime(2017, 10, 2, 0, 0)]],
  'Total months': 80},
 '36': {'courses': {'16421': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 5, 0, 0)]],
   '3525': [[datetime.datetime(2009, 10, 5, 0, 0),
     datetime.datetime(2012, 11, 25, 0, 0)]],
   '11532': [[datetime.datetime(2013, 10, 1, 0, 0),
     datetime.datetime(2015, 7, 5, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2013, 10, 1, 0, 0),
    datetime.datetime(2015, 7, 5, 0, 0)],
   [datetime.datetime(2010, 10, 1, 0, 0), datetime.datetime(2013, 7, 5, 0, 0)],
   [datetime.datetime(2009, 10, 5, 0, 0),
    datetime.datetime(2013, 7, 5, 0, 0)]],
  'Total months': 99},
 '37': {'courses': {'6530': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 11, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2011, 10, 1, 0, 0),
    datetime.datetime(2013, 7, 11, 0, 0)]],
  'Total months': 21},
 '38': {'courses': {'13502': [[datetime.datetime(2014, 10, 1, 0, 0),
     datetime.datetime(2016, 7, 6, 0, 0)]],
   '22927': [[datetime.datetime(2011, 8, 22, 0, 0),
     datetime.datetime(2014, 7, 10, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2014, 10, 1, 0, 0),
    datetime.datetime(2016, 7, 6, 0, 0)],
   [datetime.datetime(2011, 8, 22, 0, 0),
    datetime.datetime(2014, 7, 10, 0, 0)]],
  'Total months': 55},
 '39': {'courses': {'982': [[datetime.datetime(2016, 7, 7, 0, 0),
     datetime.datetime(2016, 7, 7, 0, 0)]],
   '22928': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2014, 8, 20, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2016, 7, 7, 0, 0),
    datetime.datetime(2016, 7, 7, 0, 0)],
   [datetime.datetime(2011, 9, 26, 0, 0),
    datetime.datetime(2014, 8, 20, 0, 0)]],
  'Total months': 34},
 '40': {'courses': {'22927': [[datetime.datetime(2011, 8, 22, 0, 0),
     datetime.datetime(2014, 11, 7, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2011, 8, 22, 0, 0),
    datetime.datetime(2014, 11, 7, 0, 0)]],
  'Total months': 38},
 '41': {'courses': {'22920': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 7, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2011, 10, 1, 0, 0),
    datetime.datetime(2013, 7, 7, 0, 0)]],
  'Total months': 21},
 '42': {'courses': {'6530': [[datetime.datetime(2011, 10, 3, 0, 0),
     datetime.datetime(2014, 1, 21, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2011, 10, 3, 0, 0),
    datetime.datetime(2014, 1, 21, 0, 0)]],
  'Total months': 27},
 '43': {'courses': {'23949': [[datetime.datetime(2013, 10, 1, 0, 0),
     datetime.datetime(2015, 7, 14, 0, 0)]],
   '9821': [[datetime.datetime(2010, 9, 27, 0, 0),
     datetime.datetime(2013, 7, 10, 0, 0)]]},
  'All courses periods': [[datetime.datetime(2010, 9, 27, 0, 0),
    datetime.datetime(2013, 7, 10, 0, 0)],
   [datetime.datetime(2013, 10, 1, 0, 0),
    datetime.datetime(2015, 7, 14, 0, 0)]],
  'Total months': 54},
 '44': {'courses': {'22928': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2014, 7, 10, 0, 0)]],
   '14117': [[datetime.datetime(2014, 10, 1, 0, 0),

In [19]:
import json

def date_to_timestamp(d):
    return int(d.timestamp())

for student_id, data in active_periods_of_person.items():
    for course_id, periods in active_periods_of_person[student_id]["courses"].items():
        active_periods_of_person[student_id]["courses"][course_id] = [[date_to_timestamp(date[0]), date_to_timestamp(date[1])] for date in periods]  
        
    active_periods_of_person[student_id]["All courses periods"] = [
        [date_to_timestamp(date[0]), date_to_timestamp(date[1])] for date in active_periods_of_person[student_id]["All courses periods"]]  

# with open('data.json', 'w', encoding='utf-8') as f:
#     json.dump(active_periods_of_person, f, ensure_ascii=False, indent=4, default=json_util.default)

AttributeError: 'int' object has no attribute 'timestamp'

In [18]:
active_periods_of_person

{'1': {'courses': {'17484': [[datetime.datetime(2014, 10, 1, 0, 0),
     datetime.datetime(2020, 12, 18, 16, 53, 14, 950091)]],
   '4279': [[datetime.datetime(2014, 10, 1, 0, 0),
     datetime.datetime(2017, 12, 8, 0, 0)]],
   '1': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2012, 10, 24, 0, 0)]],
   '25514': [[datetime.datetime(2018, 10, 1, 0, 0),
     datetime.datetime(2020, 12, 18, 16, 53, 14, 950091)]],
   '10253': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 5, 0, 0)]],
   '14101': [[datetime.datetime(2018, 10, 1, 0, 0),
     datetime.datetime(2020, 12, 18, 16, 53, 14, 950091)]]},
  'All courses periods': [[1412114400, 1608306794],
   [1538344800, 1608306794],
   [1412114400, 1512687600],
   [1285884000, 1372975200],
   [1285884000, 1372975200]],
  'Total months': 204},
 '2': {'courses': {'465': [[datetime.datetime(2014, 2, 24, 0, 0),
     datetime.datetime(2015, 4, 22, 0, 0)]],
   '16412': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2014, 2, 23, 0, 0)]],
   '7007': [[datetime.datetime(2018, 12, 10, 0, 0),
     datetime.datetime(2019, 11, 19, 0, 0)],
    [datetime.datetime(2017, 7, 24, 0, 0),
     datetime.datetime(2018, 11, 23, 0, 0)]]},
  'All courses periods': [[1544396400, 1574118000],
   [1500847200, 1542927600],
   [1316988000, 1429653600],
   [1316988000, 1429653600]],
  'Total months': 110},
 '3': {'courses': {'20707': [[datetime.datetime(2018, 10, 1, 0, 0),
     datetime.datetime(2020, 12, 18, 16, 53, 14, 950091)]],
   '13118': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2015, 2, 20, 0, 0)]],
   '10846': [[datetime.datetime(2015, 3, 30, 0, 0),
     datetime.datetime(2016, 10, 13, 0, 0)]],
   '20161': [[datetime.datetime(2012, 10, 1, 0, 0),
     datetime.datetime(2018, 10, 31, 0, 0)]],
   '19626': [[datetime.datetime(2018, 10, 1, 0, 0),
     datetime.datetime(2020, 12, 18, 16, 53, 14, 950091)]]},
  'All courses periods': [[1538344800, 1608306794],
   [1316988000, 1424386800],
   [1349042400, 1540940400],
   [1349042400, 1540940400]],
  'Total months': 210},
 '4': {'courses': {'10313': [[datetime.datetime(2006, 8, 10, 0, 0),
     datetime.datetime(2011, 2, 2, 0, 0)]],
   '13120': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2012, 3, 2, 0, 0)]],
   '19683': [[datetime.datetime(2015, 9, 18, 0, 0),
     datetime.datetime(2015, 10, 16, 0, 0)],
    [datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2013, 9, 20, 0, 0)]]},
  'All courses periods': [[1442527200, 1444946400],
   [1316988000, 1379628000],
   [1155160800, 1296601200],
   [1316988000, 1379628000]],
  'Total months': 99},
 '5': {'courses': {'20198': [[datetime.datetime(2012, 10, 1, 0, 0),
     datetime.datetime(2014, 11, 20, 0, 0)]],
   '19686': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2013, 9, 25, 0, 0)]],
   '20976': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2012, 1, 30, 0, 0)]]},
  'All courses periods': [[1317420000, 1327878000],
   [1316988000, 1416438000],
   [1316988000, 1416438000]],
  'Total months': 77},
 '6': {'courses': {'13142': [[datetime.datetime(2011, 9, 27, 0, 0),
     datetime.datetime(2012, 3, 15, 0, 0)]],
   '3263': [[datetime.datetime(2009, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 1, 0, 0)]],
   '24215': [[datetime.datetime(2013, 9, 30, 0, 0),
     datetime.datetime(2015, 9, 10, 0, 0)]]},
  'All courses periods': [[1254348000, 1372629600],
   [1380492000, 1441836000],
   [1254348000, 1372629600]],
  'Total months': 113},
 '7': {'courses': {'22918': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2013, 9, 30, 0, 0)]],
   '13863': [[datetime.datetime(2013, 10, 1, 0, 0),
     datetime.datetime(2014, 1, 10, 0, 0)],
    [datetime.datetime(2016, 1, 26, 0, 0),
     datetime.datetime(2016, 6, 24, 0, 0)]]},
  'All courses periods': [[1453762800, 1466719200],
   [1380578400, 1389308400],
   [1316988000, 1389308400]],
  'Total months': 34},
 '8': {'courses': {'5': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2013, 7, 4, 0, 0)]]},
  'All courses periods': [[1316988000, 1372888800]],
  'Total months': 21},
 '9': {'courses': {'6531': [[datetime.datetime(2009, 10, 1, 0, 0),
     datetime.datetime(2013, 12, 16, 0, 0)]]},
  'All courses periods': [[1254348000, 1387148400]],
  'Total months': 50},
 '10': {'courses': {'281': [[datetime.datetime(2011, 10, 3, 0, 0),
     datetime.datetime(2012, 3, 16, 0, 0)]],
   '13121': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2015, 6, 9, 0, 0)]]},
  'All courses periods': [[1316988000, 1433800800], [1317592800, 1331852400]],
  'Total months': 49},
 '11': {'courses': {'3262': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 1, 0, 0)]],
   '10250': [[datetime.datetime(2013, 9, 28, 0, 0),
     datetime.datetime(2015, 7, 8, 0, 0)]]},
  'All courses periods': [[1380319200, 1436306400], [1285884000, 1372629600]],
  'Total months': 54},
 '12': {'courses': {'3262': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 9, 30, 0, 0)]]},
  'All courses periods': [[1285884000, 1380492000]],
  'Total months': 35},
 '13': {'courses': {'19682': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2015, 6, 24, 0, 0)]]},
  'All courses periods': [[1316988000, 1435096800]],
  'Total months': 44},
 '14': {'courses': {'13123': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2012, 11, 22, 0, 0)]],
   '18206': [[datetime.datetime(2013, 10, 1, 0, 0),
     datetime.datetime(2016, 7, 8, 0, 0)]],
   '24618': [[datetime.datetime(2016, 10, 1, 0, 0),
     datetime.datetime(2017, 11, 14, 0, 0)]]},
  'All courses periods': [[1380578400, 1467928800],
   [1475272800, 1510614000],
   [1316988000, 1353538800]],
  'Total months': 59},
 '15': {'courses': {'9813': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2013, 7, 5, 0, 0)]]},
  'All courses periods': [[1316988000, 1372975200]],
  'Total months': 21},
 '16': {'courses': {'16417': [[datetime.datetime(2011, 10, 4, 0, 0),
     datetime.datetime(2014, 7, 7, 0, 0)]],
   '20055': [[datetime.datetime(2014, 10, 1, 0, 0),
     datetime.datetime(2016, 7, 8, 0, 0)]]},
  'All courses periods': [[1317679200, 1404684000], [1412114400, 1467928800]],
  'Total months': 54},
 '17': {'courses': {'13703': [[datetime.datetime(2015, 10, 1, 0, 0),
     datetime.datetime(2017, 9, 20, 0, 0)]],
   '22922': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2012, 10, 16, 0, 0)]],
   '576': [[datetime.datetime(2012, 10, 23, 0, 0),
     datetime.datetime(2015, 7, 7, 0, 0)]]},
  'All courses periods': [[1443650400, 1505858400],
   [1350943200, 1436220000],
   [1317420000, 1350338400]],
  'Total months': 67},
 '18': {'courses': {'17741': [[datetime.datetime(2013, 9, 30, 0, 0),
     datetime.datetime(2015, 10, 14, 0, 0)]],
   '6532': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 1, 0, 0)]]},
  'All courses periods': [[1380492000, 1444773600], [1285884000, 1372629600]],
  'Total months': 57},
 '19': {'courses': {'17274': [[datetime.datetime(2013, 9, 30, 0, 0),
     datetime.datetime(2017, 10, 2, 0, 0)]],
   '12019': [[datetime.datetime(2018, 10, 1, 0, 0),
     datetime.datetime(2019, 4, 17, 0, 0)]],
   '16415': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 9, 13, 0, 0)]]},
  'All courses periods': [[1285884000, 1379023200],
   [1380492000, 1506895200],
   [1538344800, 1555452000]],
  'Total months': 89},
 '20': {'courses': {'9817': [[datetime.datetime(2011, 9, 19, 0, 0),
     datetime.datetime(2013, 7, 16, 0, 0)]]},
  'All courses periods': [[1316383200, 1373925600]],
  'Total months': 21},
 '21': {'courses': {'10431': [[datetime.datetime(2014, 10, 1, 0, 0),
     datetime.datetime(2020, 12, 18, 16, 53, 14, 951114)]],
   '13127': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 7, 7, 0, 0)]]},
  'All courses periods': [[1317420000, 1404684000], [1412114400, 1608306794]],
  'Total months': 107},
 '22': {'courses': {'14798': [[datetime.datetime(2015, 10, 1, 0, 0),
     datetime.datetime(2017, 6, 19, 0, 0)]],
   '16420': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2015, 6, 19, 0, 0)]]},
  'All courses periods': [[1317420000, 1434664800], [1443650400, 1497823200]],
  'Total months': 64},
 '23': {'courses': {'3263': [[datetime.datetime(2008, 10, 1, 0, 0),
     datetime.datetime(2015, 7, 6, 0, 0)]],
   '8701': [[datetime.datetime(2017, 10, 3, 0, 0),
     datetime.datetime(2018, 10, 1, 0, 0)]],
   '10301': [[datetime.datetime(2015, 12, 3, 0, 0),
     datetime.datetime(2017, 10, 2, 0, 0)]]},
  'All courses periods': [[1222812000, 1436133600],
   [1449097200, 1506895200],
   [1449097200, 1538344800]],
  'Total months': 135},
 '24': {'courses': {'3269': [[datetime.datetime(2011, 9, 24, 0, 0),
     datetime.datetime(2013, 3, 29, 0, 0)]],
   '1030': [[datetime.datetime(2009, 9, 28, 0, 0),
     datetime.datetime(2010, 3, 2, 0, 0)]]},
  'All courses periods': [[1254088800, 1267484400], [1316815200, 1364511600]],
  'Total months': 23},
 '25': {'courses': {'3270': [[datetime.datetime(2011, 10, 8, 0, 0),
     datetime.datetime(2013, 7, 1, 0, 0)]]},
  'All courses periods': [[1318024800, 1372629600]],
  'Total months': 20},
 '26': {'courses': {'3263': [[datetime.datetime(2007, 10, 1, 0, 0),
     datetime.datetime(2013, 10, 17, 0, 0)]],
   '9958': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2012, 2, 20, 0, 0)]],
   '17808': [[datetime.datetime(2013, 10, 1, 0, 0),
     datetime.datetime(2020, 12, 18, 16, 53, 14, 951114)]]},
  'All courses periods': [[1317420000, 1329692400],
   [1380578400, 1608306794],
   [1191189600, 1608306794]],
  'Total months': 248},
 '27': {'courses': {'19693': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 6, 28, 0, 0)]]},
  'All courses periods': [[1317420000, 1403906400]],
  'Total months': 32},
 '28': {'courses': {'10301': [[datetime.datetime(2013, 9, 30, 0, 0),
     datetime.datetime(2015, 7, 16, 0, 0)]],
   '3263': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 6, 28, 0, 0)]]},
  'All courses periods': [[1380492000, 1436997600], [1285884000, 1372370400]],
  'Total months': 53},
 '29': {'courses': {'19685': [[datetime.datetime(2011, 9, 19, 0, 0),
     datetime.datetime(2013, 9, 25, 0, 0)]]},
  'All courses periods': [[1316383200, 1380060000]],
  'Total months': 24},
 '30': {'courses': {'20430': [[datetime.datetime(2014, 10, 1, 0, 0),
     datetime.datetime(2016, 7, 5, 0, 0)]],
   '13127': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 6, 27, 0, 0)]]},
  'All courses periods': [[1412114400, 1467669600], [1317420000, 1403820000]],
  'Total months': 53},
 '31': {'courses': {'20777': [[datetime.datetime(2015, 2, 9, 0, 0),
     datetime.datetime(2017, 6, 30, 0, 0)]],
   '3263': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 10, 0, 0)]],
   '24215': [[datetime.datetime(2013, 9, 30, 0, 0),
     datetime.datetime(2015, 7, 7, 0, 0)]],
   '21638': [[datetime.datetime(2017, 12, 1, 0, 0),
     datetime.datetime(2019, 7, 5, 0, 0)]],
   '4793': [[datetime.datetime(2014, 10, 3, 0, 0),
     datetime.datetime(2015, 2, 19, 0, 0)]]},
  'All courses periods': [[1285884000, 1373407200],
   [1512082800, 1562277600],
   [1412287200, 1498773600],
   [1380492000, 1498773600],
   [1380492000, 1498773600]],
  'Total months': 174},
 '32': {'courses': {'19685': [[datetime.datetime(2011, 9, 19, 0, 0),
     datetime.datetime(2014, 2, 26, 0, 0)]],
   '941': [[datetime.datetime(2011, 9, 30, 0, 0),
     datetime.datetime(2014, 6, 10, 0, 0)]]},
  'All courses periods': [[1317333600, 1402351200], [1316383200, 1402351200]],
  'Total months': 64},
 '33': {'courses': {'13125': [[datetime.datetime(2011, 10, 15, 0, 0),
     datetime.datetime(2014, 10, 4, 0, 0)]]},
  'All courses periods': [[1318629600, 1412373600]],
  'Total months': 35},
 '34': {'courses': {'9815': [[datetime.datetime(2011, 9, 19, 0, 0),
     datetime.datetime(2014, 2, 25, 0, 0)]]},
  'All courses periods': [[1316383200, 1393282800]],
  'Total months': 29},
 '35': {'courses': {'3263': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2014, 6, 26, 0, 0)]],
   '24215': [[datetime.datetime(2014, 9, 29, 0, 0),
     datetime.datetime(2017, 10, 2, 0, 0)]]},
  'All courses periods': [[1285884000, 1403733600], [1411941600, 1506895200]],
  'Total months': 80},
 '36': {'courses': {'16421': [[datetime.datetime(2010, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 5, 0, 0)]],
   '3525': [[datetime.datetime(2009, 10, 5, 0, 0),
     datetime.datetime(2012, 11, 25, 0, 0)]],
   '11532': [[datetime.datetime(2013, 10, 1, 0, 0),
     datetime.datetime(2015, 7, 5, 0, 0)]]},
  'All courses periods': [[1380578400, 1436047200],
   [1285884000, 1372975200],
   [1254693600, 1372975200]],
  'Total months': 99},
 '37': {'courses': {'6530': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 11, 0, 0)]]},
  'All courses periods': [[1317420000, 1373493600]],
  'Total months': 21},
 '38': {'courses': {'13502': [[datetime.datetime(2014, 10, 1, 0, 0),
     datetime.datetime(2016, 7, 6, 0, 0)]],
   '22927': [[datetime.datetime(2011, 8, 22, 0, 0),
     datetime.datetime(2014, 7, 10, 0, 0)]]},
  'All courses periods': [[1412114400, 1467756000], [1313964000, 1404943200]],
  'Total months': 55},
 '39': {'courses': {'982': [[datetime.datetime(2016, 7, 7, 0, 0),
     datetime.datetime(2016, 7, 7, 0, 0)]],
   '22928': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2014, 8, 20, 0, 0)]]},
  'All courses periods': [[1467842400, 1467842400], [1316988000, 1408485600]],
  'Total months': 34},
 '40': {'courses': {'22927': [[datetime.datetime(2011, 8, 22, 0, 0),
     datetime.datetime(2014, 11, 7, 0, 0)]]},
  'All courses periods': [[1313964000, 1415314800]],
  'Total months': 38},
 '41': {'courses': {'22920': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 7, 0, 0)]]},
  'All courses periods': [[1317420000, 1373148000]],
  'Total months': 21},
 '42': {'courses': {'6530': [[datetime.datetime(2011, 10, 3, 0, 0),
     datetime.datetime(2014, 1, 21, 0, 0)]]},
  'All courses periods': [[1317592800, 1390258800]],
  'Total months': 27},
 '43': {'courses': {'23949': [[datetime.datetime(2013, 10, 1, 0, 0),
     datetime.datetime(2015, 7, 14, 0, 0)]],
   '9821': [[datetime.datetime(2010, 9, 27, 0, 0),
     datetime.datetime(2013, 7, 10, 0, 0)]]},
  'All courses periods': [[1285538400, 1373407200], [1380578400, 1436824800]],
  'Total months': 54},
 '44': {'courses': {'22928': [[datetime.datetime(2011, 9, 26, 0, 0),
     datetime.datetime(2014, 7, 10, 0, 0)]],
   '14117': [[datetime.datetime(2014, 10, 1, 0, 0),
     datetime.datetime(2016, 7, 7, 0, 0)]]},
  'All courses periods': [[1412114400, 1467842400], [1316988000, 1404943200]],
  'Total months': 54},
 '45': {'courses': {'6530': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2013, 7, 6, 0, 0)]]},
  'All courses periods': [[1317420000, 1373061600]],
  'Total months': 21},
 '46': {'courses': {'24215': [[datetime.datetime(2014, 11, 14, 0, 0),
     datetime.datetime(2017, 10, 2, 0, 0)]],
   '3263': [[datetime.datetime(2009, 10, 1, 0, 0),
     datetime.datetime(2014, 10, 20, 0, 0)]]},
  'All courses periods': [[1254348000, 1413756000], [1415919600, 1506895200]],
  'Total months': 94},
 '47': {'courses': {'9817': [[datetime.datetime(2011, 9, 19, 0, 0),
     datetime.datetime(2013, 4, 22, 0, 0)]]},
  'All courses periods': [[1316383200, 1366581600]],
  'Total months': 19},
 '48': {'courses': {'22927': [[datetime.datetime(2011, 8, 22, 0, 0),
     datetime.datetime(2014, 7, 10, 0, 0)]],
   '17149': [[datetime.datetime(2014, 10, 11, 0, 0),
     datetime.datetime(2016, 6, 22, 0, 0)]]},
  'All courses periods': [[1313964000, 1404943200], [1412978400, 1466546400]],
  'Total months': 54},
 '49': {'courses': {'22925': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 9, 10, 0, 0)]]},
  'All courses periods': [[1317420000, 1410300000]],
  'Total months': 35},
 '50': {'courses': {'9817': [[datetime.datetime(2011, 9, 19, 0, 0),
     datetime.datetime(2013, 7, 1, 0, 0)]]},
  'All courses periods': [[1316383200, 1372629600]],
  'Total months': 21},
 '51': {'courses': {'13132': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 7, 4, 0, 0)]]},
  'All courses periods': [[1317420000, 1404424800]],
  'Total months': 33},
 '52': {'courses': {'13127': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 11, 27, 0, 0)]]},
  'All courses periods': [[1317420000, 1417042800]],
  'Total months': 37},
 '53': {'courses': {'19689': [[datetime.datetime(2010, 9, 29, 0, 0),
     datetime.datetime(2013, 6, 25, 0, 0)]]},
  'All courses periods': [[1285711200, 1372111200]],
  'Total months': 32},
 '54': {'courses': {'9817': [[datetime.datetime(2011, 9, 19, 0, 0),
     datetime.datetime(2013, 10, 17, 0, 0)]]},
  'All courses periods': [[1316383200, 1381960800]],
  'Total months': 24},
 '55': {'courses': {'9822': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 6, 27, 0, 0)]]},
  'All courses periods': [[1317420000, 1403820000]],
  'Total months': 32},
 '56': {'courses': {'14948': [[datetime.datetime(2014, 10, 18, 0, 0),
     datetime.datetime(2016, 7, 8, 0, 0)]],
   '13125': [[datetime.datetime(2011, 10, 15, 0, 0),
     datetime.datetime(2014, 9, 12, 0, 0)]]},
  'All courses periods': [[1318629600, 1410472800], [1413583200, 1467928800]],
  'Total months': 54},
 '57': {'courses': {'2576': [[datetime.datetime(2019, 10, 1, 0, 0),
     datetime.datetime(2020, 12, 18, 16, 53, 14, 952084)]],
   '13127': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 7, 7, 0, 0)]]},
  'All courses periods': [[1317420000, 1404684000], [1569880800, 1608306794]],
  'Total months': 47},
 '58': {'courses': {'6531': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 9, 17, 0, 0)]],
   '688': [[datetime.datetime(2015, 10, 1, 0, 0),
     datetime.datetime(2015, 12, 2, 0, 0)]]},
  'All courses periods': [[1317420000, 1410904800], [1443650400, 1449010800]],
  'Total months': 37},
 '59': {'courses': {'9817': [[datetime.datetime(2011, 9, 19, 0, 0),
     datetime.datetime(2013, 12, 19, 0, 0)]]},
  'All courses periods': [[1316383200, 1387407600]],
  'Total months': 27},
 '60': {'courses': {'9817': [[datetime.datetime(2011, 9, 19, 0, 0),
     datetime.datetime(2016, 12, 1, 0, 0)]]},
  'All courses periods': [[1316383200, 1480546800]],
  'Total months': 62},
 '61': {'courses': {'9817': [[datetime.datetime(2011, 9, 19, 0, 0),
     datetime.datetime(2013, 10, 17, 0, 0)]],
   '10169': [[datetime.datetime(2008, 10, 1, 0, 0),
     datetime.datetime(2011, 6, 28, 0, 0)]]},
  'All courses periods': [[1316383200, 1381960800], [1222812000, 1309212000]],
  'Total months': 56},
 '62': {'courses': {'19685': [[datetime.datetime(2011, 9, 19, 0, 0),
     datetime.datetime(2013, 9, 27, 0, 0)]],
   '24215': [[datetime.datetime(2013, 9, 30, 0, 0),
     datetime.datetime(2017, 10, 1, 0, 0)]],
   '7003': [[datetime.datetime(2012, 10, 1, 0, 0),
     datetime.datetime(2012, 12, 18, 0, 0)]],
   '11987': [[datetime.datetime(2017, 10, 1, 0, 0),
     datetime.datetime(2018, 7, 17, 0, 0)]]},
  'All courses periods': [[1316383200, 1380232800],
   [1349042400, 1355785200],
   [1380492000, 1531778400],
   [1380492000, 1531778400]],
  'Total months': 140},
 '63': {'courses': {'19691': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2013, 6, 4, 0, 0)]]},
  'All courses periods': [[1317420000, 1370296800]],
  'Total months': 20},
 '64': {'courses': {'13135': [[datetime.datetime(2011, 10, 3, 0, 0),
     datetime.datetime(2013, 9, 30, 0, 0)]]},
  'All courses periods': [[1317592800, 1380492000]],
  'Total months': 23},
 '65': {'courses': {'22925': [[datetime.datetime(2011, 10, 1, 0, 0),
     datetime.datetime(2014, 7, 2, 0, 0)]]},
  'All courses periods': [[1317420000, 1404252000]],